### ISSUE TITLE
SHA256 checksum

### ISSUE THREAD

**Issue by phartz** [pivotal-cf/kiln#10]
First, thank you for the great tool! It simplifies the tile development a lot.

I have a feature request. 
To upload a tile to the pivotal network its needed to provide a sha256 hash.
I implemented the needed struct and because of the [md5SumCalculator](https://github.com/pivotal-cf/kiln/blob/master/builder/tile_writer.go#L29-L31) it's easy to integrated another hash sum calculator.
If you're interested in help, I could add it to the project.
 
The create a sha256 hash instead of md5 it would be conceivable to add a flag `--sha256checksum` f.e.

`helper/file_sha256_hash_calculator.go`
https://gist.github.com/phartz/7fcc2a3be0eeaa298aca58541b36ce35

`helper/file_sha256_hash_calculator_test.go`
https://gist.github.com/phartz/a28502a9e8d3f9959f44f2992ccb467f

Regards Patrick

**Comment by mcwumbly** [comment]
@ryanmoran thanks for chiming in. I've had a reminder I keep swatting away to revisit the codesigning question too.  Hopefully soon I can make the time to ask you or others more about it.

**Comment by phartz** [comment]
@mcwumbly sorry for the late response. I'm from Europe and because of the time shift I was already in weekend ;-)
I thought I don't want to break any existing automated workflow, therefore the flag. It would also be ok to do both. 
What the parsing for workflows depends, why not writing the checksum in files. (I do this in other workflows and it simplifies things a lot.)
`mytile.pivotal.md5` and/or `mytile.pivotal.sha256` 

I only started using the tool and can just tell from my perspective. 
Thanks in advance.

**Comment by mcwumbly** [comment]
> I only started using the tool and can just tell from my perspective.

That's perfectly fine. For the workflows that you need this for, what do you think would make the most sense?  Having it output on stdout? or having a separate file? (Or something else?)

**Comment by phartz** [comment]
I would prefer a file. `mytile.pivotal.sha256` 
:-)

**Comment by ljfranklin** [comment]
Agreed, a file seems much more useful for scripting. The general pattern I've seen elsewhere (e.g. [hashicorp releases](https://releases.hashicorp.com/terraform/0.11.7/)) is a build consists of the main artifact like our `.pivotal` files, a `.sha256` file containing the checksum, and a `.sig` file to verify code-signing.

We'd be happy to accept a PR for the `.sha256` bit or you can try to convince @mcwumbly & @kenchenpcf to get it prioritized in our backlog.

**Comment by ryanmoran** [comment]
Maybe we should consider flags for both checksums. Calculating either is a non-trivial amount of time to wait for something as large as the 8GB PAS tile. It would be unfortunate to have to wait even longer when you build a tile if you don't really care about the checksums.

**Comment by mcwumbly** [comment]
Good point, @ryanmoran 

If we're gonna make a breaking change, then I'm somewhat inclined to:

1. remove the md5 checksum
1. add a flag for `--sha256`
1. wait and see whether anyone complains about not having an md5 option

Have `--sha256` write to stdout and to a file `mytile.pivotal.sha256`

**Comment by phartz** [comment]
@ljfranklin will do the PR asap. I'm on a business trip, so it could take some days.
Sorry for that.

I'll do the solution described from @mcwumbly.
Is this ok?

**Comment by mcwumbly** [comment]
@phartz - you're good to go. no need to rush!  ping us again here if you have any questions once you get into it.
