### ISSUE TITLE
`kiln bake` fails if `--stemcell-tarball` is not provided.

### ISSUE THREAD

**Issue by pianohacker** [pivotal-cf/kiln#18]
This was a regression in 0.19.0. Previous versions allowed the stemcell criteria to be manually specified in the `metadata.yml` file, but 0.19.0 and later versions fail with the following message if neither `--assets-file` or `--stemcell-tarball` are specified:

```
Reading stemcell criteria from .lock
2019/05/02 15:31:33 could not execute "bake": failed to parse stemcell: open .lock: no such file or directory
```

**Comment by mcwumbly** [comment]
@pianohacker thanks for opening this issue.

I'm not sure exactly what the best approach here is in the long term, but for now it sounds like it'd be better to not error in this case (in particular if the required info is in metadata.yml).

Would you have any interest in further specifying your desired behavior with a failing test? (and/or with a change the gets it passing?)
