### ISSUE TITLE
Add multiple --stemcell-tarball to bake command

### ISSUE THREAD

**Issue by roicos** [pivotal-cf/kiln#23]
We are using kiln bake command to build product for OpsMan like this:
```
kiln bake \
    ...
    --stemcell-tarball "$( find "p-pks-integrations/stemcells" -maxdepth 1 -name 'light-bosh-stemcell-*-google-kvm-ubuntu-*-go_agent.tgz'  -print -quit )" \
    ...
```
However if we need to support more than one stemcell (for windows and ubuntu) and kiln doesn't allow this.

Could the kiln command support a `--stemcell-directory` option as an argument to supply multiple stemcells? Here is an example: 

```
kiln bake \
    ...
    --stemcell-directory "p-pks-integrations/stemcells" \
    ...
```

**Comment by mcwumbly** [comment]
Hi @roicos, I think what you're suggesting likely makes sense. For consistency, I think the flag should probably be named `--stemcells-directory`, but aside from that, this seems OK.

I'm not sure what this would mean for the `stemcell` template helper. Per the README:

> To include information about the stemcell in your metadata you can use the `stemcell` template helper:
> 
> ```
> $ cat /path/to/metadata
> ---
> stemcell_criteria: $( stemcell )
> ```

How do you imagine that part working with multiple stemcells?

---

We don't have any immediate plans to work on this, but a PR would be welcome and we may be able to identify someone to be a more dedicated interrupt for this effort if y'all pick it up.

**Comment by spinfooser** [comment]
@mcwumbly FYI: I was pairing with @roicos, and I'm about to pick this up with a pair.

`--stemcells-directory` seems good to me. 

The stemcell template helper will need to be considered. Is it fine to maybe create a parallel stemcells_criteria key that can take multiple stemcells? I'm not super familiar with this use case, because I'm not sure our team is using it. What is the input data that could go into this key?

**Comment by spinfooser** [comment]
I found this wonderful resource. We just need to update the metadata file to use `additional_stemcells_criteria`.

An example is here:
```yaml
additional_stemcells_criteria:
  - os: windows2016
    version: 1709.19
```

Here is where I found this info: https://github.com/pivotal-cf-experimental/ops-manager-example/blob/master/example-product/metadata/example-product.yml.erb

**Comment by spinfooser** [comment]
@mcwumbly We had a quick question after looking at the code relating to directories vs a single directory for releases. We noticed that most of the other features of `kiln bake` allow for more than one directory (example: --releases-directory).

When you suggested adding `--stemcells-directory`, did you expect us to follow the convention that allows for multiple directories being passed as args?

Would it be alright if we support this behavior? We're not sure if others would use this, but this is the current pattern in the code.

```bash
kiln bake \
--stemcells-directory dir1 \
--stemcells-directory dir2
```

**Comment by evanfarrar** [comment]
I don't think it is going to wreck things either way but if other flags support merging the arguments into a list if they are supplied multiple times vs. last flag clobbers the previous invocations then I say accepting it multiple times is preferred

**Comment by evanfarrar** [comment]
This is pretty useful for contributors to your tile to get "out of tree" additions without needing to copy them into the tile repo all the time (at least that was the idea with releases):
`kiln bake --stemcells-directory ~/workspace/p-runtime/stemcells/ --stemcells-directory ~/workspace/cf-incubator/bosh-arm-stemcell/out/`
