### ISSUE TITLE
kiln validate

### ISSUE THREAD

**Issue by ciriarte** [pivotal-cf/kiln#262]
We want a `kiln validate` command.

This command will check the syntax of a Kilnfile. We want to ensure Kilnfile updates do not trigger a full deployment as they are instructions for our dependabot integration.

**Comment by crhntr** [comment]
I am considering whether we should check the contents of the Kilnfile.lock. For example,
- [ ] when there is an extra, missing, or duplicate release in the lock, it should fail
- [ ] when the release version in the lock does not pass the constraint in the Kilnfile, it should fail
- [ ] when a release in the lock is missing required fields, it should fail
