### ISSUE TITLE
Deprecate the `compile-built-releases` command and associated code

### ISSUE THREAD

**Issue by crhntr** [pivotal-cf/kiln#291]
Using an `om` deployed bosh director along with `cache-compiled-releases` is now the preferred way to create compiled releases for tiles. We should remove the previous command and associated code.

**Comment by crhntr** [comment]
@syslxg and @ciriarte, let me know when y'all are done with the changes to our scripts and I can rip it out. I doubt anyone else is using this command besides our team.

**Comment by staylor14** [comment]
Not deprecated, but removed entirely, by #306.
