### ISSUE TITLE
Kiln is grumpy when there's a dirty workspace

### ISSUE THREAD

**Issue by ciriarte** [pivotal-cf/kiln#32]
Context: https://pivotal.slack.com/messages/C0555LE4W/p1566407443390400?thread_ts=1566407442.390300&cid=C0555LE4W

**Comment by njbennett** [comment]
Specifically kiln will fail in a confusing way if there's additional `yml` files in the directory.

```
2019/08/21 17:06:06 template: tile-preprocess:3993:43: executing "tile-preprocess" at <.Subject>: nil data; no entry for key "Subject"
exit status 1`. 
```

It tries to parse whatever `yml` files it finds and the parsing fails if the `yml` doesn't have the structure of a metadata component file.

**Comment by crhntr** [comment]
I have not been able to reproduce this and it has not been an issue for years.
