### ISSUE TITLE
kiln publish command does not pass enough arguments to pivnet.NewAccessTokenOrLegacyToken

### ISSUE THREAD

**Issue by martyspiewak** [pivotal-cf/kiln#34]
It looks like the PR that was merged yesterday (https://github.com/pivotal-cf/kiln/pull/33) makes a call to `pivnet.NewAccessTokenOrLegacyToken` (https://github.com/pivotal-cf/kiln/pull/33/commits/da6a662e06c4977c7348a6c63f5b9ddbfd7f3f68#diff-a140698f609bddb589d5504a1bacf915R73).

The arguments to to this call have changed since the PR was first submitted and so the call now fails as it is expecting an additional boolean value (`skipSSLValidaiton`) to be passed in (https://github.com/pivotal-cf/go-pivnet/commit/7ce0bc6ba7876274e630722a5def9f421eb832b5#diff-ebf0811389a62f10223d76e0c0222175R97).

**Comment by crhntr** [comment]
@martys34 I just attempted to upgrade to go-pivnet `v2.0.1`; however, the go-pivnet module does not seem to be setup properly to be imported as a n>1 version per this doc: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

I will push the bump in the package to the next Kiln story.
