### ISSUE TITLE
Kiln generates invalid tiles on Windows

### ISSUE THREAD

**Issue by Proplex** [pivotal-cf/kiln#354]
Heya! It seems that newer versions of OM does not like tiles that were kiln-generated on a Windows machine. The issue is as follows:

Upon creating the tile on a Windows machine, if we upload the tile to an OM 3.0 instance, we get the error "Invalid zip file, this archive appears to use backslashes as path separators". This behavior is not noticed when the tile is generated on a Linux-based machine.

Digging through the source code a bit, it seems like we're using `filepath.Join` to add releases to the tile:
https://github.com/pivotal-cf/kiln/blob/09b39a4909dc81bd0b55912e99bb8cc561ccb751/internal/builder/tile_writer.go#L130 

Searching around shows that `filepath.Join` will return `\` for paths on Windows which [is the intended functionality,](https://github.com/golang/go/issues/30616) and that we should use `path.Join` to force paths with `/` separators.

This issue currently prevents tile generation on Windows machines for newer versions of OM. Although I haven't tested it, folks have told me this worked with earlier versions of OM; I know OM is using zlib for decompression; perhaps either zlib or the Ruby library leveraging zlib got more strict about zip validation recently?

**Comment by crhntr** [comment]
There are quite a few places in kiln where paths are constructed improperly. I suspected it might be an issue but never dug into it. Thanks for the bug report :)
