### ISSUE TITLE
Version flag doesn't overwrite 

### ISSUE THREAD

**Issue by ctaymor** [pivotal-cf/kiln#4]
When I run `kiln build` with a `--version` flag, and I have a `product_version` and `provides_product_version` specified in my tile metadata,
I expect kiln to either:
1. error, because I have provided conflicting versions
or 
2. overwrite the `product_version` and the `provides_product_version` with the version provided in the flag.

However, I observe that the final tile built by kiln retains the `product_version` and `provides_product_version` provided in the metadata, and ignores the `--version` flag.

I'm not sure if this is a bug in the documentation or in the behavior, or both, but it's confusing.

We're running kiln from commit e0b7027f0c3d01fa3e460e3115821c782db283b7.

**Comment by ctaymor** [comment]
We tried removing `product_version` and `provides_product_version` in our metadata and keeping the version flag. We expected both keys to be set to the version from the flag in the final metadata, but instead there was neither `product_version` nor `provides_product_version`.
Kiln does say it is injecting the version into the metadata however.
```
2017/12/27 17:13:38 Injecting version "1.32.7" into metadata...
```
It seems like the `--version` flag isn't working at all.

**Comment by astrieanna** [comment]
From examining the code, it appears that the required string is `1.2.3.4$PRERELEASE_VERSION$`, where ever you want the version to get plugged in. The `1`, `2`, and `3` can be any integer; the `4` has to be a single digit.

The relevant regex: https://github.com/pivotal-cf/kiln/blob/cae5a1aca0df3992545e66f94f323926efb7041f/builder/metadata_reader.go#L36

**Comment by ryanmoran** [comment]
@ctaymor @astrieanna we are still working to iron out some of these weird implementation details. We have a story in the backlog that should get picked up relatively soon: https://www.pivotaltracker.com/story/show/153490437.

This will mean that you can insert the version using a template function that looks like `$( version )`. These template functions will be used for a number of things (releases, instance groups, jobs, variables, properties). Hopefully they will make these types of implicit rules a bit less confusing.

Sorry for the beta software.
