### ISSUE TITLE
kiln version unknown

### ISSUE THREAD

**Issue by peterhaochen47** [pivotal-cf/kiln#468]
### Describe the bug

"kiln version unknown" output from running `kiln version` on MacOS

### Reproduction steps

1. brew tap pivotal-cf/kiln https://github.com/pivotal-cf/kiln
1. brew install kiln
1. kiln version

### Expected behavior

`kiln version` shows correct kiln version

**Comment by crhntr** [comment]
Please check your path and ensure the brew installed binary is first. You (or some script) may have installed a kiln from source. I just ran your commands on my machine and got this

```
$ kiln version
kiln version 0.89.0
$
```

Having said that, I think we should remove the "kiln version " prefix.

**Comment by pvaramballypivot** [comment]
Confirmed that the functionality works. Closing the issue.

```
$ kiln version
kiln version 0.89.0
```
