### ISSUE TITLE
Upgrading to Go 1.23 looks like it is causing counterfeiter to have a bad day

### ISSUE THREAD

**Issue by crhntr** [pivotal-cf/kiln#508]
After I run `go mod edit -go 1.23`
When I run `go generate ./...`
Then I get the following error:
```
target is not a named type
exit status 1
internal/commands/init_test.go:20: running "go": exit status 1
```

I tried updating counterfeiter. We should do that. It did not help in this case.

I have a few suspicions on how to fix this and will give it a try sometime soon but for now we need to pin to 1.22. We have till around March 2025 to figure this out.

**Comment by dlinsley** [comment]
Resolved in #505
