### ISSUE TITLE
[Feature Request] Subcomand to print interpolated metadata.yml

### ISSUE THREAD

**Issue by albertoleal** [pivotal-cf/kiln#8]
Hi,

We run a `hancraft-linter` tool in our CI which reads the metadata.yml and compare all the properties against the releases. With kiln we would need to bake a tile and then untar it. 

How about adding a subcomand in Kiln that we can run and get the interpolated metadata without baking the whole tile?

Thanks,
Kura and Alberto

**Comment by albertoleal** [comment]
Hi @mcwumbly! For our test we need the real releases in order to inspect all bosh properties.

Our linter works like this:
- Reads all properties we have in our metadata.yml; and
- Checks if all those properties exist in each `spec` bosh release. If not, it fails.

**Comment by mcwumbly** [comment]
I see, in that case, forget the `--stub-releases` flag, but does snagging the metadata file per the above zip command do what you need?

**Comment by mcwumbly** [comment]
@albertoleal I took a look at your commit above and now I think my earlier comment stands. If you already have your own real releases there, your linter can still reference them, even if you use the `--stub-releases` flag in the `bake` command. Doing so will just skip adding the releases to the tile, which should make the bake command quicker.  And if you want to further optimize things, you can use the `unzip` command I wrote above to skip unzipping anything else in the tile (though at that point, it may not be worth it).

If you do those things I think you've optimized things as well as what you're asking for here, aside from the UX nicety of having a dedicated command.

**Comment by albertoleal** [comment]
Awesome, `--stub-releases` did the trick! Thanks @mcwumbly :)
